##This will be deployment script for ArgoCD
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-test
spec:
  containers:
  -  name: nginx
     image: nginx:latest
     ports:
     -  containerPort: 8082
   
     
