##This will be deployment script for ArgoCD
apiVersion: apps/v1
kind: Deployment
metadata:
    name: apps-deployment
    labels:
        app: centos
    
spec:
    replicas: 2
    selector:  
        matchLabels: 
            app: centos
    template:
        metadata:
          labels:
            app: centos
        spec:        
          containers:
          -   name: centos
              image: salahabbasi/centos:83
              ports:
              -   containerPort: 8084
          restartPolicy: Always
    
     
