pipeline {
 agent any
 stages {
   stage ('testing') {
     steps {
	  sh 'echo "fail"; exit 1'
	 }
   }
    }
 post {
  always {
  echo 'always run'
  }
  success {
   echo 'on success'
  }
  failure {
  echo 'on failure'
  }
  unstable {
  echo 'run when got stabled'
  }
  }
}
