pipeline {
 agent any 
 
 environment {
	registry = "https://hub.docker.com/"
	registryCredentials = 'DockerID'
	IMAGE_TAG = "${build_number}"
 
	}
 stages {
  
  stage ('get branch') {
		steps {
			echo '$GIT_BRANCH'
			  }
		}
  
  stage ('build image') {
		steps {
			echo 'Build docker image'
		    script{
				sh ( script: '''
				cd docker/ 
				docker images -a
				docker build -t salahabbasi/centos:$build_number . 
				docker images -a
				''')
				}	
			  }
			}
  stage ('scan image') {
		steps {
			echo 'scanning container for vulnerability, baad me karenge'
			}
		}
  stage ('image Push') 
		{
		steps {
			echo 'Pushing image to dockerhub'
		    script {
				docker.withRegistry('',registryCredentials)
					{
					sh 'docker push salahabbasi/centos:$build_number'
					}
				   }	
			  }
		} 
  
 }

 post 
 {
	success {
		echo 'Pipeline is working fine'
	}
	failure {
		echo 'Pipeline is not configured as expected'
	}
	always {
		echo 'Always keep practicing to be the best'
	}
 }
}
